JetBrains/qodana-docker

2023.3/base/dotnet.Dockerfile

This reverts commit d1a3938b9ee5d6654cde5fa3c384db3ffdc1b71b.

Revert ".nuget directory should be writable (#13)"

---

next/dotnet/included_plugins.txt

Plugin com.intellij.hardcodedPasswords is required for qodana plugin in Rider product.

Adjust dependencies for qodana-dotnet:241

---

2024.1/go/included_plugins.txt
2024.1/js/included_plugins.txt
2024.1/jvm/included_plugins.txt
2024.1/php/included_plugins.txt
2024.1/python/included_plugins.txt
2024.1/ruby/included_plugins.txt

FlexInspect: Add kotlin-scirpting to qodana image plugins

kotlin-scripting

---

next/go/included_plugins.txt
next/js/included_plugins.txt
next/php/included_plugins.txt
next/python/included_plugins.txt
next/ruby/included_plugins.txt

QD-8215 FlexInspect: Add kotlin scripting plugin to non jvm images

---

next/android-community/.dockerignore
next/dotnet/.dockerignore
next/go/.dockerignore
next/js/.dockerignore
next/jvm-community/.dockerignore
next/jvm/.dockerignore
next/php/.dockerignore
next/python-community/.dockerignore
next/python/.dockerignore
next/ruby/.dockerignore
next/rust/.dockerignore

Stop ignoring plugin-classpath.txt

---

next/dotnet/included_plugins.txt

Fix missing com.jetbrains.rider.rdct-shared dep

---

next/android/included_plugins.txt
next/dotnet/included_plugins.txt

 QD-9327 Add required plugin for C++ support in Rider

---

2024.2/python/included_plugins.txt
next/python/included_plugins.txt

Add missing plugins

---

2024.1/base/python.Dockerfile
2024.1/python-community/Dockerfile
2024.1/python/Dockerfile
2024.2/base/python.Dockerfile
2024.2/python-community/Dockerfile
2024.2/python/Dockerfile
next/base/python.Dockerfile

After this, there should be no problems with poetry, and any poetry project should do only
```
poetry install
```

QD-9255 Fix permissions for `poetry` inside conda env

---

2024.1/python/included_plugins.txt

QD-9594 `intellij.notebooks.ui` to QDPY

---

2024.2/python/included_plugins.txt

QD-9594 com.intellij.notebooks.core* to 242

---

feed/releases.json

Update feed with new 242 distributives

---

next/android-community/.dockerignore
next/android/.dockerignore
next/dotnet/.dockerignore
next/go/.dockerignore
next/js/.dockerignore
next/jvm-community/.dockerignore
next/jvm/.dockerignore
next/php/.dockerignore
next/python-community/.dockerignore
next/python/.dockerignore
next/ruby/.dockerignore
next/rust/.dockerignore

QD-9913 Remove plugin-classpath.txt from 251

---

2024.3/android-community/.dockerignore
2024.3/android/.dockerignore
2024.3/dotnet/.dockerignore
2024.3/go/.dockerignore
2024.3/js/.dockerignore
2024.3/jvm-community/.dockerignore
2024.3/jvm/.dockerignore
2024.3/php/.dockerignore
2024.3/python-community/.dockerignore
2024.3/python/.dockerignore
2024.3/ruby/.dockerignore
2024.3/rust/.dockerignore

QD-9913 Remove plugin-classpath.txt from 243

---

.github/workflows/base.yml

Unclude ruby 3.3-243 base image for Qodana builds

QD-10231 Add ruby 3.3-243 image

---

next/android/disabled_plugins.txt
next/cnova/disabled_plugins.txt
next/dotnet/disabled_plugins.txt
next/go/disabled_plugins.txt
next/js/disabled_plugins.txt
next/jvm/disabled_plugins.txt
next/php/disabled_plugins.txt
next/python/disabled_plugins.txt
next/ruby/disabled_plugins.txt
next/rust/disabled_plugins.txt

QD-9913 Specify disabled_plugins.txt in qodana-docker

---

feed/releases.json

Bump dotnet native 242 build

---

feed/releases.json

QD-9913 - Update native feed

---

feed/releases.json

Revert QDNET distributive and fix incorrectly generated releases.json

---

feed/releases.json

QD-9913 - Update native distributives

---

2024.3/android-community/Dockerfile
2024.3/android/Dockerfile
2024.3/cpp/Dockerfile
2024.3/dotnet-community/Dockerfile
2024.3/dotnet/Dockerfile
2024.3/go/Dockerfile
2024.3/js/Dockerfile
2024.3/jvm-community/Dockerfile
2024.3/jvm/Dockerfile
2024.3/php/Dockerfile
2024.3/python-community/Dockerfile
2024.3/python/Dockerfile

QD-10347 Add Dockerfiles to 2024.3 image builds

---

feed/releases.json

QD-10360 - Update native distributives

---

feed/releases.json

QD-10371 - Update 243 native distributives

---

feed/releases.json

QD-10487 - Update 243 native distributives

---

feed/releases.json

QD-10795 add new dotnet release build 243.24609.130

---

feed/releases.json

QD-10876 - Update 243 native distributives

---

.github/workflows/base-bullseye.yml

QD-8148 Fix bullseye builds

---

2024.3/base/docker-bake.hcl
2025.1/base/docker-bake.hcl

https://youtrack.jetbrains.com/issue/QD-11127/Add-ruby-3.4-to-docker-images

QD-11127 add ruby 3.4 image

---

2025.1/base/templates/intellij.Dockerfile.j2
2025.1/base/templates/thirdparty.Dockerfile.j2
next/base/templates/intellij.Dockerfile.j2
next/base/templates/thirdparty.Dockerfile.j2

Missed ';' for if-else-fi
dotnet and cpp rc builds fail

QD-8148 add ; before fi

---

2025.1/cpp/disabled_plugins.txt
2025.1/cpp/included_plugins.txt
next/cpp/included_plugins.txt

CPP-43482: Disable ctest plugin in qodana-cpp

---

next/go/included_plugins.txt
next/js/included_plugins.txt

QD-11525 Add database plugin (sql inspections) to js and go images

---

next/jvm-community/included_plugins.txt
next/python-community/included_plugins.txt

Add JSON plugin to community distribution because it disappeared (for some reason?)

---

feed/releases.json

QD-11547 - Qodana Linters Release 2025.1

---

.github/scripts/release-matrix.py
.github/workflows/ci.yml

This change ensures that no releases will be left out from CI except those explicitly excluded.

QD-11734: Implement dynamic gh-actions matrix for checking releases

---

2025.1/android-community/Dockerfile
2025.1/android/Dockerfile
2025.1/base/templates/intellij.Dockerfile.j2
2025.1/cpp/Dockerfile
2025.1/dotnet/Dockerfile
2025.1/go/Dockerfile
2025.1/js/Dockerfile
2025.1/jvm-community/Dockerfile
2025.1/jvm/Dockerfile
2025.1/php/Dockerfile
2025.1/python-community/Dockerfile
2025.1/python/Dockerfile
2025.1/ruby/Dockerfile
2025.2/base/templates/intellij.Dockerfile.j2
next/base/templates/intellij.Dockerfile.j2

QD-11775 update releases.json

---

feed/releases.json

QD-12104 add eap natives
